### ISSUE TITLE
Example "Login" is not working properly

### ISSUE THREAD

**Issue by federico-pepe** [Milchreis/uibooster-for-processing#1]
Hi @Milchreis, thank you very much for this awesome library! I was trying it going through the examples and the Login.pde in the folder 3_Complex_Dialogs is not working correctly.

I'll do a pull request to fix it immediately :)

**Comment by Milchreis** [comment]
Hi @federico-pepe and thank you for your kind words and the PR.
I don't know where my mind was when I wrote this example 😄
