### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by FringeNet** [Milchreis/uibooster-for-processing#10]
I would like to be able to force a text input/dialog box/etc. to be created in focus. 
For example, a fullscreen sketch is in focus, when the user does something to cause a UiBooster GUI window to appear, the window that's created is drawn in front of the fullscreen sketch.

I am not sure how difficult this is, I hope it is possible.

thx in advance

**Comment by Milchreis** [comment]
Hi @JamesDemaine-wit 

could you fix this issue for yourself? I tried the fullscreen mode with an input-dialog on Windows 10 without any problems.

**Comment by FringeNet** [comment]
Hi @Milchreis, I am using the P2D renderer, I solved the issue by stopping the loop before creating the dialog boxes, as well as casting the Surface to an openGL window, then using the .setVisible(boolean); method. 
`com.jogamp.newt.opengl.GLWindow window = (com.jogamp.newt.opengl.GLWindow)(((PSurfaceJOGL)surface).getNative());`
`window.setVisible(false);`
Source: https://stackoverflow.com/questions/39107750/java-and-processing-3-0-frame-class-deprecated-is-there-an-alternative
Doing this seemed to solve my issue.

The reason I opened an issue was in the hope of getting the ability to tell UiBooster to grab focus from the fullscreen P2D renderer. 

Hope this explains it well enough

**Comment by FringeNet** [comment]
I was just looking through the most recent issue on here with the P2D renderer. I tried what you suggested before, I found that same solution to a similar problem elsewhere (I forgot where I put the link now sorry), the issue is that surface does not always behave the way it's expected to, so casting it manually to an openGL window/surface solved it for me.
