### ISSUE TITLE
Table Dialog

### ISSUE THREAD

**Issue by leuwenn** [Milchreis/uibooster-for-processing#16]
Hello,

I can't figure out how the data is stored in the "Table dialog".
Is it an ArrayList or a Table ?
I can't figure out how to recover the data once the window is closed.

I apologize for the basic question.

Regards,

**Comment by Milchreis** [comment]
hi @leuwenn 

thank you for the issue. The given data for the table is converted internally to the Java Swing DefaultTableModel object ([look here](https://github.com/Milchreis/UiBooster/blob/b7d3d26911ff2f50d20e81d32b31b52ae4757ab8/src/main/java/de/milchreis/uibooster/components/TablePanel.java#L21)).
If you close the window the method `UiBooster.showTable(/* ... */)` will return the latest state of the table as 2d-array of Strings (type: String[][]). It's the same data format that the method will expect as input type. 

```java
// Creates a table and shows the user
String[][] modifiedData = new UiBooster().showTable( 
        new String[][]{
                {"Jimmy Johnson", "35", "Zombieland"},
                {"Danny Durango", "23", "Hangover"},
                {"Larry Berry", "54", ""}
        },
        Arrays.asList("Name", "Age", "Favorite movie"),
        "Favorite movies");

// Creates another table with the given modified data 
new UiBooster().showTable( 
        modifiedData,
        Arrays.asList("Name", "Age", "Favorite movie"),
        "Favorite movies");
```

I hope it answers your question. If not, please ask again in more detail 😊
