### ISSUE TITLE
How to remove/replace Java icon on dialogs

### ISSUE THREAD

**Issue by luiscastilho** [Milchreis/uibooster-for-processing#17]
Hello,
First of all, thanks for UiBooster! It's really easy to use and has helped me a lot. :)

I have a small problem, and maybe it's just me doing something wrong. Since uibooster-for-processing v1.14.0, the confirmation dialog changed from this:

![uibooster-old](https://user-images.githubusercontent.com/3590078/178131736-74be598e-a742-478d-b72c-eb5fa20b347f.png)

To this:

![uibooster-new](https://user-images.githubusercontent.com/3590078/178131740-8f7e9db0-3930-4033-8a0a-19377c431fcf.png)

I believe it's because Darcula theme was replaced by Flatlaf, right? The problem I have is that I would like to remove or at least replace the Java icon on the top left corner of the new dialog window. I tried the code below but the icon didn't change. Am I doing something wrong? Is there any way I can do that?

```
uiDialogs = new UiBooster(UiBoosterOptions.Theme.DARK_THEME, dataPath("path/to/my/icon.png"));
```

Thanks for your help

**Comment by Milchreis** [comment]
hi luis,

thank you for reporting this issue. The following dialogs will probably have the problem with (custom) window-icon:

- showInfoDialog
- showWarningDialog
- showErrorDialog
- showTextInputDialog
- showConfirmDialog
- showSelectionDialog
- showFileSelection
- showDirectorySelection
- showWaitingDialog

I will take a look and try to find a solution 😊

**Comment by luiscastilho** [comment]
Great! Thanks for looking into this. :)

**Comment by Milchreis** [comment]
Hi luis,

in the main UiBooster project, I fixed [this issue](https://github.com/Milchreis/UiBooster/issues/71) for the dialogs listed. There is one more issue to solve until I create the next release. The next version will also update the uibooster-for-processing project.


Thank you for your patience and the support for this project 😊

**Comment by luiscastilho** [comment]
Hey @Milchreis, just wanted to let you know that release 1.14.4 of UiBooster didn't update the uibooster-for-processing project. Latest uibooster-for-processing release still is 1.14.3.

**Comment by Milchreis** [comment]
Hi @luiscastilho 

some weeks ago I prepared all to publish this lib to version 1.14.4., but to be honest I forget to finished this process. Now, I want to update to version 1.15.0 (because a new font chooser was integrated), but than I found a bug in the color chooser (whichs also updated in 1.15.0).

I created an issue to the colorpicker project. I hope this will be fixed fast, than I will update UiBooster and for processing too. 
Sorry for the delay for the updates in this project.

**Comment by luiscastilho** [comment]
No problem at all. I will wait for 1.15.0 then. Thanks again.

**Comment by Milchreis** [comment]
The bug int he colorpicker lib by @dheid was fixed by him in light speed. Now the new version is published and ready to use. 😊

**Comment by dheid** [comment]
I'm not sure if the bug with the icon is really fixed by me. I think it's the flatlaf version I used when submitting the fontchooser to your library. You can try downgrading to the old version of flatlaf, but it would be more code mature if the problem could be forward fixed.
