### ISSUE TITLE
Question: Possible to close form dialog?

### ISSUE THREAD

**Issue by deranku** [Milchreis/uibooster-for-processing#19]
Hi, 

thanks for releasing UIBooster, it really helps setting up a UI.

Is it possible to close a form dialog, other than closing its window? I'd like to do simple 'ok' and 'cancel' buttons on the bottom of the dialog. In the form class doesn't seem to be a method for that.

best,
Philip

**Comment by deranku** [comment]
Nevermind, sorry to bother,` form.close();` did the trick--

**Comment by Milchreis** [comment]
Don't worry. I am glad that UiBooster is useful to you and it works for your needs ☺️
