### ISSUE TITLE
Calling a function when a slider has changed

### ISSUE THREAD

**Issue by federico-pepe** [Milchreis/uibooster-for-processing#3]
Hi @Milchreis! I am still testing the library and I was wondering if there’s a way to determine if a slider’s value has changed. I went through the javadoc but couldn’t find anything related to this.

**Comment by Milchreis** [comment]
Hi @federico-pepe,

at the moment UiBooster doesn't support this kind of interaction. Most of the dialogs are implemented as "input and return" UI. Especially for Processing I added the run() method for forms to keep the UI running without blocking the whole app.

The event driven approach you want to use is interessesting, too. What is you special use case? Maybe I add this issue to the UiBooster project.

**Comment by federico-pepe** [comment]
I think that most of the time people need an UI in Processing is to control parameters on a  generative design sketches. 

That's exactly the thing I am working on right now: I'm controlling with sliders some parameters of a sketch and it would be awesome to be able to call the function that draws the shape when a slider is moved.

I can't leave everything in the draw() function because I am also using noise function so I don't want the sketch to keep changing. [This is the code](https://gist.github.com/federico-pepe/0c30ff8de6cfa4799523b0de1ae44290) I'm working on.

**Comment by Milchreis** [comment]
Thank you @federico-pepe for the explaination. I think it's a very good idea and really interessting for other user, too. I created an issue in the UiBooster project, because it's affects the core code.

**Comment by Milchreis** [comment]
Hi @federico-pepe

a new release is out now. There is a ChangeListner implemented. Hope you like it and it fits for your use case.

Here is an [example](https://github.com/Milchreis/uibooster-for-processing/blob/master/examples/3_Forms/SimpleFormChangeListener/SimpleFormChangeListener.pde#L34)

**Comment by federico-pepe** [comment]
I just did a quick test and it looks great!

Thank you very much for implementing this so quickly
