### ISSUE TITLE
Is there a way to change the colors of the windows?

### ISSUE THREAD

**Issue by qewer33** [Milchreis/uibooster-for-processing#7]
I just started using this library and is there a way to change the general colors of the windows?

**Comment by Milchreis** [comment]
hi @qewer33 

UiBooster supports the OS native look and feel and a dark theme. You can change it as follows:
```java
UiBooster booster = new UiBooster(
    new UiBoosterOptions(
        UiBoosterOptions.Theme.DARK_THEME  // or UiBoosterOptions.Theme.OS_NATIVE
    )
);
```

Unfortunately there is currently no possibility to adjust the colors of the windows.

**Comment by qewer33** [comment]
Okay thanks! OS Native look will do it for me.

**Comment by qewer33** [comment]
Oh and sorry I forgot to ask but can you give me the rgb values of the main dark theme color?

**Comment by Milchreis** [comment]
The dark theme is based on the darcula look and feel. You can find all settings here:
https://github.com/bulenkov/Darcula/blob/master/src/com/bulenkov/darcula/darcula.properties
