### ISSUE TITLE
Splash screen doesn't work properly in P2D renderer

### ISSUE THREAD

**Issue by ppboo** [Milchreis/uibooster-for-processing#9]
Hello @Milchreis,
I'm very happy to use this library and everything works fine but I've just tried using the splash screen in a project that is set to P2D, but the main sketch window is overlaying the splash screen. Is there any way to hide the main window and show the splash screen when running the sketch?

I also like to know if it's possible to include this library in a project meant for commercial purposes, I'm making this app for a client and he wants to sell it. Would that be a trouble for me and him?

Thanks!

**Comment by Milchreis** [comment]
Hi @ppboo, 

the P2D mode works different, but I figured out a way to make it possible. You can use the variable `surface` to access the window, but in P2D the window in setup is not the same as in draw. I moved the splashscreen from setup into a separate thread to avoid the one-time show in draw.

```java
import uibooster.*;
import uibooster.components.*;

void setup() {
  size(10, 10, P2D);
  // Hide the window 
  surface.setVisible(false);
  // Run splash screen in a separate thread
  thread("showSplash");
}

void showSplash() {
  UiBooster booster = new UiBooster();

  String splashImage = dataPath("splash.png");
  Splashscreen splash = booster.showSplashscreen(splashImage);

  // do your stuff

  delay(1500); // delay for presentation

  splash.hide();
  // Show the window
  surface.setVisible(true);
}

void draw() {
  background(10);
}
```

It's more a Processing issue than UiBooster, but I hope it works for your use case 😊
This library is published on MIT license. You can used it in commercial projects, too. If you get rich, than you could buy me a coffee on [kofi](https://ko-fi.com/L4L21072C) if you want 😉
